exp_name: pacs_kaggle_fagdr_uda_truncated

mode: train
n_classes: 5
aux_classes: 3
method: 'rotate'

network:
    arch: resnet18_fc

datasets:
    src:
        type: 'rotate'
        name: ['KaggleR']
        batch_size: 16
        num_workers: 4
        limit: false
        val_size: 0.1
        bias_whole_image: 0.7
        aux_classes: 3
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.3150, 0.2218, 0.1578]
            std: [0.3002, 0.2178, 0.1720]
    tar:
        type: 'rotate'
        name: 'FGADR'
        split: train
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        bias_whole_image: 0.7
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        normalize:
            mean: [0.4557, 0.2588, 0.1325]
            std: [0.2856, 0.1855, 0.1356]

    test:
        type: 'rotate'
        name: 'FGADR'
        split: test
        batch_size: 16
        num_workers: 4
        limit: false
        aux_classes: 3
        img_transform:
            jitter: 0
            random_resize_crop:
                size: [222, 222]
        normalize:
            mean: [0.4557, 0.2588, 0.1325]
            std: [0.2856, 0.1855, 0.1356]

testing:
    model: ''

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 40
    optimizer:
        name: 'sgd'
        lr: 0.1
        weight_decay: 0.01
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: step
        step_size: 8 # num_epochs * 0.8
    src_aux_weight: 0.1
    tar_aux_weight: 0.1
    tar_entropy_weight: 0.1
    src_kld_weight: 0.1
    tar_kld_weight: 0.1
    only_non_scrambled: false
#    class_weight: [0.6100, 0.8400, 0.6500, 0.9400, 0.9500]
    class_weight: [0.15288221, 0.21052631, 0.16290726, 0.23558897, 0.23809524]
