exp_name: imageclef_i_p_cdan

mode: train
n_classes: 12
method: 'cdan'

network:
    arch: resnet50_fc

datasets:
    src:
        type: 'image'
        name: ['I']
        batch_size: 36
        num_workers: 4
        limit: false
        val_size: 0.0
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        jig_transform:
            tile_random_grayscale: 0.1
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]
    tar:
        type: 'image'
        name: 'P'
        split: train
        batch_size: 36
        num_workers: 4
        limit: false
        img_transform:
            jitter: 0
            random_horiz_flip: 0
            random_resize_crop:
                size: [222, 222]
                scale: [0.8, 1.0]
        jig_transform:
            tile_random_grayscale: 0.1
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]

    test:
        type: 'image'
        name: 'P'
        split: test
        batch_size: 36
        num_workers: 4
        limit: false
        img_transform:
            jitter: 0
            random_resize_crop:
                size: [222, 222]
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.222, 0.225]

testing:
    model: ''

training:
    resume: ''
    num_print_epoch: 10
    num_epochs: 800
    optimizer:
        name: 'sgd'
        lr: 0.001
        weight_decay: 0.0005
        momentum: 0.9
        nesterov: true
    lr_scheduler:
        name: inv_lr
    transfer_loss_weight: 1.0
